version: '3.5'

services:
  mkdocs:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /code/
    ports:
      - ${MKDOCS_PORT:-8000}:8000
    entrypoint: /code/serve.sh
